export default [
    {
        "name": "John Doe",
        "age": 30,
        "city": "New York",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
    {
        "name": "Alain Doe",
        "age": 30,
        "city": "Dhaka",
        "email": "john.doe@example.com",
        "isSubscribed": true,
    },
]